project:
  type: website
  output-dir: docs
  

website:
  title: "ANÁLISE DISCRIMINANTE, PROBIT e LOGIT - Aplicações em R"
  navbar:
    left:
      - href: index.qmd
        text: Análise discriminante
      - href: logit_probit.qmd
        text: Logit e Probit

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



