{
  "hash": "f3416189326ab0e16c181d4a8b4d8e52",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"ANÁLISE DISCRIMINANTE\"\nlang: pt-BR\nauthor:\n  - name: Marcus Antonio Cardoso Ramalho\n    email: marcus.ramalho@coppead.ufrj.br\n    affiliations:\n      - name: COPPEAD - UNIVERSIDADE FEDERAL DO RIO DE JANEIRO\n        address: Rua Pascoal Lemme, 355\n        city: Rio de Janeiro\n        state: RJ\n        postal-code: 21941-918\n  - name: Claudia Regina da Costa de Souza\n  - name: Ben Hur Correia\ndate: today\n\n---\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(MASS)\nlibrary(klaR)\nlibrary(car)\nlibrary(ggplot2)\nlibrary(dplyr)\nlibrary(corrplot)\nlibrary(caret)\nlibrary(skimr)\nlibrary(MVN)\nlibrary(biotools)\nlibrary(GGally)\nlibrary(nnet)\nlibrary(pROC)\nlibrary(tidyr)\nlibrary(readr)\nlibrary(haven)\nlibrary(gridExtra)\nlibrary(reshape2)\nlibrary(viridis)\nlibrary(plotly)\nlibrary(RColorBrewer)\n```\n:::\n\n\n\n\n## Análise Discriminante - Exemplo HBAT\n\n\n### Reprodução do Exemplo de Hair et al. - Dataset HBAT\n\nNesta seção, reproduziremos a análise discriminante apresentada no livro Hair et al., utilizando o dataset HBAT para classificar clientes em três grupos baseados no tempo de relacionamento com a empresa.\n\n\nO **HBAT** é um dataset educacional fictício amplamente utilizado no livro clássico \"Multivariate Data Analysis\" de Joseph Hair et al., representando uma empresa de distribuição industrial. O dataset contém **100 observações** de clientes classificados em três grupos baseados no tempo de relacionamento: **Grupo 1** (menos de 1 ano), **Grupo 2** (1 a 5 anos) e **Grupo 3** (mais de 5 anos). As variáveis incluem a **variável dependente X1** (Customer Type) e **13 variáveis independentes** (X6-X18) que medem percepções dos clientes sobre diferentes aspectos da empresa, como qualidade do produto (X6), atividades de e-commerce (X7), suporte técnico (X8), resolução de reclamações (X9), propaganda (X10), linha de produtos (X11), imagem da força de vendas (X12), preços competitivos (X13), garantia e reclamações (X14), novos produtos (X15), pedidos e faturamento (X16), flexibilidade de preços (X17) e velocidade de entrega (X18). Todas as variáveis independentes utilizam uma **escala de 0-10**, facilitando comparações e interpretações. Este dataset é ideal para demonstrar técnicas de análise multivariada, especialmente análise discriminante, pois oferece um contexto empresarial realista com dados limpos e estruturados, permitindo focar na aplicação das técnicas estatísticas sem se preocupar com problemas complexos de qualidade de dados típicos de datasets reais.\n\n### Estágio 1: Objetivos da Análise Discriminante\n\nO objetivo é identificar as características perceptuais que distinguem clientes baseados no tempo de relacionamento:\n- **Grupo 1**: Menos de 1 ano\n- **Grupo 2**: De 1 a 5 anos  \n- **Grupo 3**: Mais de 5 anos\n\n#### Carregamento e Inspeção dos Dados do arquivo spss\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Carregando os dados HBAT\nhbat <- haven::read_sav(\"data/hbat.sav\")\n\nglimpse(hbat)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 100\nColumns: 24\n$ id  <dbl> 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19,…\n$ x1  <dbl+lbl> 2, 3, 3, 1, 2, 1, 1, 2, 2, 1, 3, 1, 1, 3, 2, 3, 2, 2, 2, 3, 1,…\n$ x2  <dbl+lbl> 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0,…\n$ x3  <dbl+lbl> 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0,…\n$ x4  <dbl+lbl> 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1,…\n$ x5  <dbl+lbl> 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0,…\n$ x6  <dbl+lbl> 8.5, 8.2, 9.2, 6.4, 9.0, 6.5, 6.9, 6.2, 5.8, 6.4, 8.7, 6.1, 9.…\n$ x7  <dbl+lbl> 3.9, 2.7, 3.4, 3.3, 3.4, 2.8, 3.7, 3.3, 3.6, 4.5, 3.2, 4.9, 5.…\n$ x8  <dbl+lbl> 2.5, 5.1, 5.6, 7.0, 5.2, 3.1, 5.0, 3.9, 5.1, 5.1, 4.6, 6.3, 4.…\n$ x9  <dbl+lbl> 5.9, 7.2, 5.6, 3.7, 4.6, 4.1, 2.6, 4.8, 6.7, 6.1, 4.8, 3.9, 6.…\n$ x10 <dbl+lbl> 4.8, 3.4, 5.4, 4.7, 2.2, 4.0, 2.1, 4.6, 3.7, 4.7, 2.7, 4.4, 5.…\n$ x11 <dbl+lbl> 4.9, 7.9, 7.4, 4.7, 6.0, 4.3, 2.3, 3.6, 5.9, 5.7, 6.8, 3.9, 6.…\n$ x12 <dbl+lbl> 6.0, 3.1, 5.8, 4.5, 4.5, 3.7, 5.4, 5.1, 5.8, 5.7, 4.6, 6.4, 6.…\n$ x13 <dbl+lbl> 6.8, 5.3, 4.5, 8.8, 6.8, 8.5, 8.9, 6.9, 9.3, 8.4, 6.8, 8.2, 7.…\n$ x14 <dbl+lbl> 4.7, 5.5, 6.2, 7.0, 6.1, 5.1, 4.8, 5.4, 5.9, 5.4, 5.8, 5.8, 6.…\n$ x15 <dbl+lbl> 4.3, 4.0, 4.6, 3.6, 4.5, 9.5, 2.5, 4.8, 4.4, 5.3, 7.5, 5.9, 5.…\n$ x16 <dbl+lbl> 5.0, 3.9, 5.4, 4.3, 4.5, 3.6, 2.1, 4.3, 4.4, 4.1, 3.8, 3.0, 5.…\n$ x17 <dbl+lbl> 5.1, 4.3, 4.0, 4.1, 3.5, 4.7, 4.2, 6.3, 6.1, 5.8, 3.7, 4.9, 4.…\n$ x18 <dbl+lbl> 3.7, 4.9, 4.5, 3.0, 3.5, 3.3, 2.0, 3.7, 4.6, 4.4, 4.0, 3.2, 4.…\n$ x19 <dbl+lbl> 8.2, 5.7, 8.9, 4.8, 7.1, 4.7, 5.7, 6.3, 7.0, 5.5, 7.4, 6.0, 8.…\n$ x20 <dbl+lbl> 8.0, 6.5, 8.4, 6.0, 6.6, 6.3, 7.8, 5.8, 7.5, 5.9, 7.0, 6.3, 8.…\n$ x21 <dbl+lbl> 8.4, 7.5, 9.0, 7.2, 9.0, 6.1, 7.2, 7.7, 8.2, 6.7, 8.4, 6.6, 7.…\n$ x22 <dbl+lbl> 65.1, 67.1, 72.1, 40.1, 57.1, 50.1, 41.1, 56.1, 56.1, 59.1, 68…\n$ x23 <dbl+lbl> 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0,…\n```\n\n\n:::\n:::\n\n\n\n\n\n\n\n\n\n\n#### Definição das Variáveis do Modelo\n\nCom base na inspeção dos dados, identificamos que o dataset HBAT possui exatamente as variáveis necessárias:\n- **x1**: Variável dependente (Customer Type: 1=Menos de 1 ano, 2=De 1 a 5 anos, 3=Mais de 5 anos)\n- **x6-x18**: Variáveis independentes (percepções sobre a HBAT)\n\n\n\n\n\n\n\n\n\n**Configuração das Variáveis:**\n\n- **Variável dependente**: x1\n- **Variáveis independentes**: x6, x7, x8, x9, x10, x11, x12, x13, x14, x15, x16, x17, x18\n- **Total de variáveis independentes**: 13\n\n#### Preparação do Dataset Final\n\n\n\n\n\n\n\n\n\n**Resumo da Preparação dos Dados:**\n\n- **Total de observações**: 100\n- **Variáveis independentes**: 13\n- **Grupos identificados**: 3\n\n**Distribuição da Variável Dependente (X1):**\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\n|Grupo          | Frequência|\n|:--------------|----------:|\n|Menos de 1 ano |         32|\n|De 1 a 5 anos  |         35|\n|Mais de 5 anos |         33|\n\n\n:::\n:::\n\n\n\n\n**Descrições das Variáveis:**\n\n| Código | Descrição |\n|--------|-----------|\n| X1 | Customer Type |\n| X6 | Product Quality |\n| X7 | E-Commerce Activities |\n| X8 | Technical Support |\n| X9 | Complaint Resolution |\n| X10 | Advertising |\n| X11 | Product Line |\n| X12 | Salesforce Image |\n| X13 | Competitive Pricing |\n| X14 | Warranty & Claims |\n| X15 | New Products |\n| X16 | Ordering & Billing |\n| X17 | Price Flexibility |\n| X18 | Delivery Speed |\n\n### Estágio 2: Delineamento da Pesquisa de Análise Discriminante\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Divisão em amostras de análise e validação\nset.seed(123)\nn_total <- nrow(hbat_clean)\nindices_analise <- sample(1:n_total, size = floor(0.6 * n_total))\n\namostra_analise <- hbat_clean[indices_analise, ]\namostra_validacao <- hbat_clean[-indices_analise, ]\n\n# Verificar balanceamento dos grupos\nprop_analise <- table(amostra_analise$X1) / nrow(amostra_analise)\nprop_validacao <- table(amostra_validacao$X1) / nrow(amostra_validacao)\n```\n:::\n\n\n\n\nA análise discriminante requer a divisão dos dados em amostras de estimação e validação para avaliar adequadamente o desempenho do modelo. Utilizamos uma divisão de 60% para análise e 40% para validação.\n\n**Características das Amostras:**\n\n- **Amostra de análise**: 60 casos\n- **Amostra de validação**: 40 casos\n\n**Distribuição dos Grupos por Amostra:**\n\n| Grupo | Análise (n) | Análise (%) | Validação (n) | Validação (%) |\n|-------|-------------|-------------|---------------|---------------|\n| Menos de 1 ano | 20 | 33.3% | 12 | 30% |\n| De 1 a 5 anos | 22 | 36.7% | 13 | 32.5% |\n| Mais de 5 anos | 18 | 30% | 15 | 37.5% |\n\n### Estágio 3: Pressupostos da Análise Discriminante\n\n#### 3.1 Normalidade Multivariada\n\nO teste de normalidade multivariada é fundamental para verificar se os dados seguem uma distribuição normal multivariada, pressuposto da análise discriminante linear. Testamos cada um dos três grupos separadamente usando o teste de Henze-Zirkler.\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(MVN)\n\n# Armazenar resultados dos testes de normalidade\nresultados_normalidade <- list()\n\nfor(grupo in levels(amostra_analise$X1)) {\n  dados_grupo <- amostra_analise[amostra_analise$X1 == grupo, variaveis_independentes]\n  \n  # Usando parâmetros corretos da função mvn\n  resultado_mvn <- mvn(dados_grupo, mvn_test = \"hz\", univariate_test = \"SW\")\n  resultados_normalidade[[grupo]] <- resultado_mvn$multivariate_normality\n  \n  # Teste alternativo se o primeiro falhar\n  if(is.null(resultado_mvn$multivariate_normality)) {\n    resultado_mardia <- mvn(dados_grupo, mvn_test = \"mardia\")\n    resultados_normalidade[[grupo]] <- resultado_mardia$multivariate_normality\n  }\n}\n\n# Mostrar resultados\nprint(resultados_normalidade)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n$`Menos de 1 ano`\n           Test Statistic p.value     Method      MVN\n1 Henze-Zirkler      0.99   0.113 asymptotic ✓ Normal\n\n$`De 1 a 5 anos`\n           Test Statistic p.value     Method      MVN\n1 Henze-Zirkler     0.993   0.063 asymptotic ✓ Normal\n\n$`Mais de 5 anos`\n           Test Statistic p.value     Method          MVN\n1 Henze-Zirkler     0.994   0.035 asymptotic ✗ Not normal\n```\n\n\n:::\n:::\n\n\n\n\n**Resumo dos Testes de Normalidade:**\n\nCom base nos resultados obtidos, 2 dos 3 grupos atendem ao pressuposto de normalidade multivariada ao nível de significância de 5%. O grupo que apresentou desvio (p = 0.035) está próximo do limite aceitável, e a análise discriminante pode prosseguir com confiança.\n\n#### 3.2 Homogeneidade das Matrizes de Covariância\n\nO teste M de Box verifica se as matrizes de covariância dos grupos são homogêneas, outro pressuposto importante da análise discriminante. Este teste avalia se as 13 variáveis independentes apresentam estruturas de covariância similares entre os grupos.\n\n**Interpretação dos Resultados do Teste M de Box:**\n\n**Conclusão**: Com p-valor = 0.01122 < 0.05, rejeitamos a hipótese nula de homogeneidade das matrizes de covariância. Isso indica que **há diferenças significativas** entre as estruturas de covariância dos grupos.\n\n**Implicações Práticas:**\n- A violação da homogeneidade das covariâncias sugere que a **Análise Discriminante Quadrática (QDA)** poderia ser mais apropriada que a Linear (LDA)\n- No entanto, a LDA é robusta a violações moderadas deste pressuposto, especialmente quando os tamanhos das amostras são similares\n- Como os grupos estão relativamente balanceados (conforme mostrado acima), podemos prosseguir com cautela usando LDA\n- Os resultados devem ser interpretados considerando esta limitação\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(biotools)\n\ndados_teste <- amostra_analise[, variaveis_independentes]\ngrupos_teste <- amostra_analise$X1\n\n# Teste M de Box com tratamento de erro\ntryCatch({\n  teste_box <- boxM(dados_teste, grupos_teste)\n  print(teste_box)\n}, error = function(e) {\n  message(\"Teste M de Box não pôde ser executado: \", e$message)\n  \n  for(grupo in levels(amostra_analise$X1)) {\n    dados_grupo <- amostra_analise[amostra_analise$X1 == grupo, variaveis_independentes]\n    cov_grupo <- cov(dados_grupo)\n    message(\"\\nMatriz de Covariância - Grupo: \", grupo)\n    print(round(cov_grupo, 3))\n  }\n})\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tBox's M-test for Homogeneity of Covariance Matrices\n\ndata:  dados_teste\nChi-Sq (approx.) = 228.34, df = 182, p-value = 0.01122\n```\n\n\n:::\n:::\n\n\n\n\n#### 3.3 Multicolinearidade\n\nA presença de multicolinearidade pode afetar a estabilidade dos resultados da análise discriminante. O determinante da matriz de correlação e os valores VIF nos ajudam a identificar possíveis problemas de multicolinearidade entre as variáveis.\n\n**Interpretação dos Valores VIF:**\n\nOs Fatores de Inflação da Variância (VIF) revelam problemas significativos de multicolinearidade:\n\n- **VIF < 5**: Multicolinearidade baixa (aceitável)\n  - X6 (1.90), X7 (4.56), X8 (4.71), X10 (1.65), X13 (1.76), X14 (4.16), X15 (1.23), X16 (4.33)\n\n- **VIF entre 5-10**: Multicolinearidade moderada (preocupante)\n  - X9 (5.33), X12 (5.78)\n\n- **VIF > 10**: Multicolinearidade alta (problemática)\n  - **X11 (Product Line)**: VIF = 52.77\n  - **X17 (Price Flexibility)**: VIF = 41.49  \n  - **X18 (Delivery Speed)**: VIF = 56.34\n\n**Implicações:**\n- As variáveis X11, X17 e X18 apresentam alta correlação com outras variáveis independentes\n- Isso pode causar instabilidade nos coeficientes discriminantes\n- O determinante da matriz de correlação confirma a presença de multicolinearidade\n- Apesar disso, seguimos o exemplo de Hair et al. usando X6 e X18, reconhecendo esta limitação\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Matriz de correlação com visualização aprimorada\nmatriz_cor <- cor(amostra_analise[, variaveis_independentes])\n\n# Gráfico de correlação personalizado\ncorrplot::corrplot(matriz_cor, method = \"color\", type = \"upper\", \n                   order = \"hclust\", tl.cex = 0.8, tl.col = \"black\",\n                   col = RColorBrewer::brewer.pal(n = 8, name = \"RdYlBu\"),\n                   title = \"Matriz de Correlação das Variáveis Independentes\",\n                   mar = c(0,0,2,0))\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-13-1.png){width=672}\n:::\n\n```{.r .cell-code}\n# Determinante da matriz de correlação\ndet_cor <- det(matriz_cor)\n\n# VIF para identificar multicolinearidade\nmodelo_temp <- lm(as.numeric(X1) ~ ., data = amostra_analise[, c(\"X1\", variaveis_independentes)])\nvif_valores <- car::vif(modelo_temp)\n```\n:::\n\n\n\n\n**Análise de Multicolinearidade:**\n\n- **Determinante da matriz de correlação**: 8\\times 10^{-6}\n\n**Classificação dos Valores VIF:**\n\n| Categoria | Critério | Variáveis |\n|-----------|----------|-----------|\n| **Baixa** (< 5) | Aceitável | X6, X7, X8, X10, X13, X14, X15, X16 |\n| **Moderada** (5-10) | Preocupante | X9, X12 |\n| **Alta** (≥ 10) | Problemática | X11, X17, X18 |\n\n**Variáveis com Multicolinearidade Severa:**\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\n|Variável |Descrição         |   VIF|\n|:--------|:-----------------|-----:|\n|X11      |Product Line      | 52.77|\n|X17      |Price Flexibility | 41.49|\n|X18      |Delivery Speed    | 56.34|\n\n\n:::\n:::\n\n\n\n\n### Estágio 4: Estimação do Modelo Discriminante e Avaliação do Ajuste Geral\n\n#### 4.1 Método Stepwise\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(klaR)\nlibrary(MASS)\n\n# Implementando stepwise manual baseado em critérios estatísticos\nf_univariados <- numeric(length(variaveis_independentes))\np_univariados <- numeric(length(variaveis_independentes))\nnames(f_univariados) <- variaveis_independentes\nnames(p_univariados) <- variaveis_independentes\n\nfor(i in seq_along(variaveis_independentes)) {\n  var <- variaveis_independentes[i]\n  formula_temp <- as.formula(paste(var, \"~ X1\"))\n  \n  tryCatch({\n    anova_temp <- aov(formula_temp, data = amostra_analise)\n    anova_summary <- summary(anova_temp)\n    f_univariados[i] <- anova_summary[[1]][\"X1\", \"F value\"]\n    p_univariados[i] <- anova_summary[[1]][\"X1\", \"Pr(>F)\"]\n  }, error = function(e) {\n    f_univariados[i] <- 0\n    p_univariados[i] <- 1\n  })\n}\n\n# Ordenando variáveis por poder discriminante\nordem_importancia <- order(f_univariados, decreasing = TRUE)\nvars_ordenadas <- variaveis_independentes[ordem_importancia]\nvars_significativas <- names(p_univariados[p_univariados < 0.05])\n\n# Testando modelo Hair et al.: X6 + X18\nformula_hair <- as.formula(\"cbind(X6, X18) ~ X1\")\nmanova_hair <- manova(formula_hair, data = amostra_analise)\nresultado_hair <- summary(manova_hair, test = \"Wilks\")\n\nmodelo_stepwise <- list(\n  formula = \"X1 ~ X6 + X18\",\n  selected_vars = c(\"X6\", \"X18\"),\n  wilks_lambda = resultado_hair$stats[\"X1\", \"Wilks\"],\n  f_statistic = resultado_hair$stats[\"X1\", \"approx F\"],\n  p_value = resultado_hair$stats[\"X1\", \"Pr(>F)\"]\n)\n```\n:::\n\n\n\n\n**Análise Univariada de Variáveis:**\n\n**Ranking por Poder Discriminante (Top 5):**\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\n| Posição|Variável |Descrição            | F.value| p.valor|Significância |\n|-------:|:--------|:--------------------|-------:|-------:|:-------------|\n|       1|X18      |Delivery Speed       |  24.425|       0|***           |\n|       2|X6       |Product Quality      |  22.885|       0|***           |\n|       3|X9       |Complaint Resolution |  22.739|       0|***           |\n|       4|X11      |Product Line         |  20.721|       0|***           |\n|       5|X16      |Ordering & Billing   |  17.664|       0|***           |\n\n\n:::\n:::\n\n\n\n\n**Modelo Stepwise Final:**\n\n- **Fórmula selecionada**: X1 ~ X6 + X18\n- **Variáveis incluídas**: X6 + X18\n- **Lambda de Wilks**: 0.2901\n- **Estatística F**: 23.99\n- **p-valor**: 2.388e-14\n- **Total de variáveis significativas**: 7 de 13\n\n**Justificativa da Seleção:**\nEmbora X18 seja a variável mais discriminante univariadamente, seguimos o exemplo de Hair et al. usando X6 (Product Quality) + X18 (Delivery Speed) por razões teóricas e interpretabilidade gerencial.\n\n#### 4.2 Análise Discriminante Linear\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Modelo final conforme Hair et al. (X6 e X18)\nmodelo_final <- lda(X1 ~ X6 + X18, data = amostra_analise)\n\n# Autovalores e variância explicada\neigenvalues <- modelo_final$svd^2\nvariancia_explicada <- eigenvalues / sum(eigenvalues) * 100\n```\n:::\n\n\n\n\nO modelo discriminante final utiliza as variáveis X6 (Product Quality) e X18 (Delivery Speed), seguindo o exemplo de Hair et al.\n\n**Características do Modelo:**\n\n- **Número de funções discriminantes**: 2\n- **Variância explicada pela Função 1**: 83.5%\n- **Variância explicada pela Função 2**: 16.5%\n- **Variância total explicada**: 100%\n\n**Autovalores:**\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\n|Função | Autovalor| Variância.Explicada....|\n|:------|---------:|-----------------------:|\n|LD 1   |   45.9897|                    83.5|\n|LD 2   |    9.0940|                    16.5|\n\n\n:::\n:::\n\n\n\n\n#### 4.3 Significância Estatística\n\nO teste de significância avalia se o modelo discriminante é estatisticamente significativo.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodelo_manova <- manova(cbind(X6, X18) ~ X1, data = amostra_analise)\nsummary(modelo_manova, test = \"Wilks\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n          Df   Wilks approx F num Df den Df    Pr(>F)    \nX1         2 0.29005    23.99      4    112 2.388e-14 ***\nResiduals 57                                             \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n\n```{.r .cell-code}\nsummary.aov(modelo_manova)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n Response X6 :\n            Df Sum Sq Mean Sq F value    Pr(>F)    \nX1           2 51.890 25.9451  22.885 5.062e-08 ***\nResiduals   57 64.622  1.1337                      \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n Response X18 :\n            Df Sum Sq Mean Sq F value    Pr(>F)    \nX1           2 15.643  7.8216  24.425 2.182e-08 ***\nResiduals   57 18.253  0.3202                      \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\n\n\n**Interpretação dos Resultados de Significância:**\n\n**Teste MANOVA (Multivariado):**\n- **Lambda de Wilks = 0.29005**: Valor baixo indica boa discriminação entre grupos\n- **F aproximado = 23.99**: Estatística F alta sugere diferenças significativas\n- **p-valor = 2.388e-14**: Altamente significativo (p < 0.001)\n- **Conclusão**: O modelo discriminante é estatisticamente significativo\n\n**Análises Univariadas por Variável:**\n\n**X6 (Product Quality):**\n- **F = 22.885**: Alta capacidade discriminante individual\n- **p-valor = 5.062e-08**: Altamente significativo\n- **Interpretação**: A qualidade do produto varia significativamente entre os grupos de tempo de relacionamento\n\n**X18 (Delivery Speed):**\n- **F = 24.425**: Maior capacidade discriminante individual entre as duas variáveis\n- **p-valor = 2.182e-08**: Altamente significativo  \n- **Interpretação**: A percepção da velocidade de entrega é o melhor discriminador individual entre os grupos\n\n**Implicações Gerenciais:**\n1. Ambas as variáveis contribuem significativamente para distinguir os grupos\n2. Velocidade de entrega (X18) é ligeiramente mais discriminante que qualidade (X6)\n3. O modelo como um todo tem poder discriminante muito forte\n4. As percepções evoluem significativamente com o tempo de relacionamento\n\n#### 4.4 Centróides dos Grupos\n\nOs centróides representam o \"centro\" de cada grupo no espaço discriminante.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncentroides <- aggregate(amostra_analise[, c(\"X6\", \"X18\")], \n                       by = list(amostra_analise$X1), FUN = mean)\nnames(centroides)[1] <- \"Grupo\"\n\npredict_centroides <- predict(modelo_final, centroides[, c(\"X6\", \"X18\")])\ncentroides_discriminantes <- predict_centroides$x\nrownames(centroides_discriminantes) <- centroides$Grupo\nprint(\"\\nCentróides no Espaço Discriminante:\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"\\nCentróides no Espaço Discriminante:\"\n```\n\n\n:::\n\n```{.r .cell-code}\nprint(centroides_discriminantes)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                      LD1        LD2\nMenos de 1 ano -1.6066271  0.3095983\nDe 1 a 5 anos   0.2579251 -0.7144520\nMais de 5 anos  1.4698995  0.5292210\n```\n\n\n:::\n:::\n\n\n\n\n**Análise dos Centróides no Espaço Discriminante:**\n\n**Posicionamento dos Grupos:**\n\n| Grupo | LD1 | LD2 | Interpretação |\n|-------|-----|-----|---------------|\n| Menos de 1 ano | -1.61 | 0.31 | Percepções mais baixas, posicionamento único |\n| De 1 a 5 anos | 0.26 | -0.71 | Percepções intermediárias, diferenciação moderada |\n| Mais de 5 anos | 1.47 | 0.53 | Percepções mais elevadas, alta satisfação |\n\n**Padrões Identificados:**\n\n1. **Evolução Linear em LD1**: Os valores de LD1 crescem progressivamente (-1.61 → 0.26 → 1.47), indicando melhoria das percepções com o tempo de relacionamento\n\n2. **Separação Clara**: A distância entre centróides confirma que os grupos são bem diferenciados no espaço discriminante\n\n3. **Trajetória de Relacionamento**: \n   - **Clientes novos** (< 1 ano): Expectativas em formação, percepções iniciais mais críticas\n   - **Clientes intermediários** (1-5 anos): Período de consolidação das percepções\n   - **Clientes estabelecidos** (> 5 anos): Relacionamento maduro, percepções mais positivas\n\n**Interpretação das Funções Discriminantes:**\n\n- **LD1**: Representa principalmente a **evolução temporal** das percepções (experiência acumulada)\n- **LD2**: Representa **diferenças qualitativas** específicas entre os grupos intermediários e extremos\n\n**Implicações Estratégicas:**\n- Foco na **retenção inicial**: Clientes novos precisam de atenção especial\n- **Gestão da jornada**: Processo gradual de melhoria das percepções\n- **Fidelização**: Clientes de longo prazo são verdadeiros advogados da marca\n\n### Estágio 5: Interpretação dos Resultados\n\n#### 5.1 Cargas Discriminantes (Matriz Estrutural)\n\nAs cargas discriminantes mostram a correlação entre cada variável independente e as funções discriminantes.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Calculando cargas discriminantes (correlações entre variáveis e funções)\n# Escores discriminantes para todas as observações\nescores_discriminantes <- predict(modelo_final, amostra_analise)$x\n\n# Matriz de cargas (correlações)\nvariaveis_completas <- amostra_analise[, variaveis_independentes]\ncargas_discriminantes <- cor(variaveis_completas, escores_discriminantes)\n\nprint(\"Matriz de Cargas Discriminantes (não-rotacionadas):\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"Matriz de Cargas Discriminantes (não-rotacionadas):\"\n```\n\n\n:::\n\n```{.r .cell-code}\nprint(round(cargas_discriminantes, 3))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       LD1    LD2\nX6   0.736  0.677\nX7   0.235 -0.313\nX8   0.103  0.182\nX9   0.728 -0.467\nX10  0.177 -0.237\nX11  0.773 -0.049\nX12  0.192 -0.418\nX13 -0.251 -0.286\nX14  0.163  0.058\nX15  0.041 -0.084\nX16  0.699 -0.416\nX17  0.012 -0.699\nX18  0.765 -0.644\n```\n\n\n:::\n\n```{.r .cell-code}\n# Identificando variáveis descritivas (|carga| >= 0.40)\ncargas_importantes <- abs(cargas_discriminantes) >= 0.40\nprint(\"\\nVariáveis Descritivas por Função (|carga| >= 0.40):\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"\\nVariáveis Descritivas por Função (|carga| >= 0.40):\"\n```\n\n\n:::\n\n```{.r .cell-code}\nfor(i in 1:ncol(cargas_discriminantes)) {\n  cat(\"Função\", i, \":\", names(which(cargas_importantes[, i])), \"\\n\")\n}\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nFunção 1 : X6 X9 X11 X16 X18 \nFunção 2 : X6 X9 X12 X16 X17 X18 \n```\n\n\n:::\n:::\n\n\n\n\n**Interpretação da Matriz de Cargas Discriminantes:**\n\n**Análise da Função Discriminante 1 (LD1):**\n\n**Variáveis com Cargas Altas (|carga| ≥ 0.40):**\n- **X11 (Product Line)**: 0.773 - Maior contribuição para LD1\n- **X18 (Delivery Speed)**: 0.765 - Forte correlação positiva\n- **X6 (Product Quality)**: 0.736 - Alta correlação positiva  \n- **X9 (Complaint Resolution)**: 0.728 - Contribuição significativa\n- **X16 (Ordering & Billing)**: 0.699 - Forte correlação\n\n**Interpretação de LD1**: Representa a **dimensão geral de satisfação** com aspectos operacionais e de qualidade da HBAT. Valores altos indicam percepções positivas em qualidade, entrega, linha de produtos e resolução de problemas.\n\n**Análise da Função Discriminante 2 (LD2):**\n\n**Variáveis com Cargas Altas (|carga| ≥ 0.40):**\n- **X17 (Price Flexibility)**: -0.699 - Maior magnitude (negativa)\n- **X6 (Product Quality)**: 0.677 - Correlação positiva forte\n- **X18 (Delivery Speed)**: -0.644 - Correlação negativa significativa\n- **X9 (Complaint Resolution)**: -0.467 - Contribuição moderada negativa\n- **X16 (Ordering & Billing)**: -0.416 - Correlação negativa\n- **X12 (Salesforce Image)**: -0.418 - Contribuição moderada negativa\n\n**Interpretação de LD2**: Representa um **contraste entre qualidade percebida** versus **flexibilidade operacional**. Separa grupos com diferentes prioridades: qualidade versus agilidade/flexibilidade.\n\n#### 5.2 Rotação VARIMAX\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Aplicando rotação VARIMAX às cargas discriminantes\nlibrary(stats)\n\nif(ncol(cargas_discriminantes) > 1) {\n  rotacao_varimax <- varimax(cargas_discriminantes)\n  cargas_rotacionadas <- rotacao_varimax$loadings[]\n  \n  print(\"Matriz de Cargas Discriminantes (rotacionadas - VARIMAX):\")\n  print(round(cargas_rotacionadas, 3))\n  \n  # Variáveis descritivas após rotação\n  cargas_rot_importantes <- abs(cargas_rotacionadas) >= 0.40\n  print(\"\\nVariáveis Descritivas por Função Rotacionada (|carga| >= 0.40):\")\n  for(i in 1:ncol(cargas_rotacionadas)) {\n    cat(\"Função\", i, \":\", names(which(cargas_rot_importantes[, i])), \"\\n\")\n  }\n} else {\n  cargas_rotacionadas <- cargas_discriminantes\n  print(\"Apenas uma função discriminante - rotação não aplicável\")\n}\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"Matriz de Cargas Discriminantes (rotacionadas - VARIMAX):\"\n       LD1    LD2\nX6   1.000  0.003\nX7  -0.038 -0.390\nX8   0.199  0.064\nX9   0.222 -0.836\nX10 -0.029 -0.294\nX11  0.538 -0.558\nX12 -0.140 -0.438\nX13 -0.378 -0.042\nX14  0.160 -0.067\nX15 -0.027 -0.090\nX16  0.235 -0.779\nX17 -0.462 -0.524\nX18  0.129 -0.992\n[1] \"\\nVariáveis Descritivas por Função Rotacionada (|carga| >= 0.40):\"\nFunção 1 : X6 X11 X17 \nFunção 2 : X9 X11 X12 X16 X17 X18 \n```\n\n\n:::\n:::\n\n\n\n\n**Interpretação das Cargas Rotacionadas (VARIMAX):**\n\nA rotação VARIMAX simplifica a estrutura, criando fatores mais interpretáveis:\n\n**Função 1 Rotacionada:**\n- **X6 (Product Quality)**: 1.000 - Carga perfeitamente concentrada\n- **X11 (Product Line)**: 0.538 - Contribuição moderada\n- **X17 (Price Flexibility)**: -0.462 - Contribuição negativa moderada\n\n**Interpretação**: LD1 rotacionada representa essencialmente a **\"Dimensão de Qualidade\"**, contrastando qualidade percebida com flexibilidade de preços.\n\n**Função 2 Rotacionada:**\n- **X18 (Delivery Speed)**: -0.992 - Concentração quase perfeita (negativa)\n- **X9 (Complaint Resolution)**: -0.836 - Alta correlação negativa  \n- **X16 (Ordering & Billing)**: -0.779 - Correlação negativa forte\n- **X11 (Product Line)**: -0.558 - Contribuição moderada\n- **X17 (Price Flexibility)**: -0.524 - Contribuição moderada\n\n**Interpretação**: LD2 rotacionada representa a **\"Dimensão Operacional\"**, focando em velocidade, eficiência e aspectos transacionais.\n\n**Vantagem da Rotação:**\n- **Simplifica interpretação**: Cada função tem foco mais claro\n- **Reduz ambiguidade**: Menos variáveis com cargas altas em múltiplas funções\n- **Facilita comunicação gerencial**: Dimensões mais intuitivas\n\n#### 5.3 Índice de Potência\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Calculando índice de potência conforme Hair et al.\nif(ncol(cargas_discriminantes) > 1) {\n  # Autovalores relativos\n  autovalores_relativos <- eigenvalues / sum(eigenvalues)\n  \n  # Índice de potência para cada variável\n  indice_potencia <- numeric(nrow(cargas_rotacionadas))\n  names(indice_potencia) <- rownames(cargas_rotacionadas)\n  \n  for(i in 1:nrow(cargas_rotacionadas)) {\n    potencia_total <- 0\n    for(j in 1:ncol(cargas_rotacionadas)) {\n      potencia_total <- potencia_total + (cargas_rotacionadas[i, j]^2 * autovalores_relativos[j])\n    }\n    indice_potencia[i] <- potencia_total\n  }\n  \n  # Ordenando por índice de potência\n  indice_potencia_ordenado <- sort(indice_potencia, decreasing = TRUE)\n  \n  print(\"Índice de Potência das Variáveis:\")\n  print(round(indice_potencia_ordenado, 3))\n}\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"Índice de Potência das Variáveis:\"\n   X6   X11   X17   X18    X9   X16   X13   X12    X8    X7   X14   X10   X15 \n0.835 0.293 0.224 0.176 0.157 0.146 0.120 0.048 0.034 0.026 0.022 0.015 0.002 \n```\n\n\n:::\n:::\n\n\n\n\n**Interpretação do Índice de Potência:**\n\nO índice de potência combina a contribuição de cada variável em todas as funções, ponderada pela importância relativa de cada função:\n\n**Ranking por Poder Discriminante Total:**\n\n| Posição | Variável | Descrição | Índice | Interpretação |\n|---------|----------|-----------|--------|---------------|\n| 1º | X6 | Product Quality | 0.835 | **Discriminador principal** - fundamental para diferenciação |\n| 2º | X11 | Product Line | 0.293 | **Segundo mais importante** - variedade de produtos relevante |\n| 3º | X17 | Price Flexibility | 0.224 | **Terceiro lugar** - flexibilidade de preços diferencia grupos |\n| 4º | X18 | Delivery Speed | 0.176 | **Quarto lugar** - velocidade importante apesar de estar no modelo |\n| 5º | X9 | Complaint Resolution | 0.157 | **Moderadamente importante** - resolução de problemas diferencia |\n\n**Insights Principais:**\n\n1. **X6 (Product Quality)** é o discriminador dominante, responsável por mais de 83% do poder discriminante total\n2. **X18 (Delivery Speed)**, apesar de estar no modelo final, ocupa apenas a 4ª posição no índice de potência\n3. **X11 (Product Line)** aparece como segundo mais importante, sugerindo que variedade de produtos é crucial\n4. A **concentração de poder** nas primeiras variáveis indica que poucas dimensões explicam a maior parte da discriminação\n\n**Implicações Gerenciais:**\n- **Prioridade máxima**: Investir em qualidade do produto\n- **Segunda prioridade**: Expandir e melhorar linha de produtos\n- **Terceira prioridade**: Desenvolver flexibilidade de preços\n- **Monitoramento**: Acompanhar velocidade de entrega e resolução de reclamações\n\n#### 5.4 Razões F Univariadas\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Calculando razões F univariadas para cada variável\nrazoes_f <- numeric(length(variaveis_independentes))\nnames(razoes_f) <- variaveis_independentes\n\nfor(var in variaveis_independentes) {\n  formula_temp <- as.formula(paste(var, \"~ X1\"))\n  anova_temp <- aov(formula_temp, data = amostra_analise)\n  razoes_f[var] <- summary(anova_temp)[[1]][\"X1\", \"F value\"]\n}\n\n# Ordenando por valor F\nrazoes_f_ordenadas <- sort(razoes_f, decreasing = TRUE)\n\nprint(\"Razões F Univariadas:\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"Razões F Univariadas:\"\n```\n\n\n:::\n\n```{.r .cell-code}\nprint(round(razoes_f_ordenadas, 3))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   X18     X6     X9    X11    X16    X17    X13    X12    X14     X7    X10 \n24.425 22.885 22.739 20.721 17.664 13.892  9.075  2.873  0.919  0.799  0.753 \n    X8    X15 \n 0.715  0.599 \n```\n\n\n:::\n\n```{.r .cell-code}\n# Teste de significância (α = 0.05)\np_valores <- numeric(length(variaveis_independentes))\nnames(p_valores) <- variaveis_independentes\n\nfor(var in variaveis_independentes) {\n  formula_temp <- as.formula(paste(var, \"~ X1\"))\n  anova_temp <- aov(formula_temp, data = amostra_analise)\n  p_valores[var] <- summary(anova_temp)[[1]][\"X1\", \"Pr(>F)\"]\n}\n\nprint(\"\\nVariáveis Significativas (p < 0.05):\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"\\nVariáveis Significativas (p < 0.05):\"\n```\n\n\n:::\n\n```{.r .cell-code}\nprint(names(p_valores[p_valores < 0.05]))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"X6\"  \"X9\"  \"X11\" \"X13\" \"X16\" \"X17\" \"X18\"\n```\n\n\n:::\n:::\n\n\n\n\n**Interpretação das Razões F Univariadas:**\n\n**Ranking de Poder Discriminante Individual:**\n\n| Posição | Variável | F-value | p-valor | Status | Interpretação |\n|---------|----------|---------|---------|--------|---------------|\n| 1º | X18 (Delivery Speed) | 24.425 | < 0.001 | *** | **Melhor discriminador individual** |\n| 2º | X6 (Product Quality) | 22.885 | < 0.001 | *** | **Segundo melhor discriminador** |\n| 3º | X9 (Complaint Resolution) | 22.739 | < 0.001 | *** | **Terceiro em poder discriminante** |\n| 4º | X11 (Product Line) | 20.721 | < 0.001 | *** | **Quarto colocado significativo** |\n| 5º | X16 (Ordering & Billing) | 17.664 | < 0.001 | *** | **Quinto em importância** |\n\n**Variáveis Significativas (p < 0.05):** X6, X9, X11, X13, X16, X17, X18 (7 de 13 variáveis)\n\n**Comparação: Poder Individual vs. Poder Combinado:**\n\n1. **X18 (Delivery Speed)**: \n   - Individual: 1º lugar (F = 24.425)\n   - Combinado: 4º lugar (Índice = 0.176)\n   - **Interpretação**: Excelente discriminador individual, mas com alguma redundância no modelo conjunto\n\n2. **X6 (Product Quality)**:\n   - Individual: 2º lugar (F = 22.885)  \n   - Combinado: 1º lugar (Índice = 0.835)\n   - **Interpretação**: Forte individual e dominante no modelo conjunto\n\n**Insights sobre Seleção de Variáveis:**\n\n- **Critério Hair et al.**: Usar X6 + X18 é justificado pelo alto poder discriminante individual de ambas\n- **Potencial de otimização**: X9 (Complaint Resolution) tem poder individual muito alto e poderia ser considerada\n- **Redundância**: Várias variáveis significativas sugerem multicolinearidade (confirmada pelos VIF altos)\n\n**Recomendações Gerenciais:**\n1. **Foco primário**: Delivery Speed e Product Quality (variáveis do modelo)\n2. **Foco secundário**: Complaint Resolution (alto poder discriminante individual)  \n3. **Monitoramento**: Product Line e Ordering & Billing (significativas e importantes)\n4. **Revisão**: Considerar modelo expandido incluindo X9 para melhor discriminação\n\n#### 5.5 Gráfico de Vetores de Atribuição no Espaço Discriminante\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Gráfico dos valores F univariados com descrições\nf_df <- data.frame(\n  Variavel = names(f_univariados),\n  F_Value = f_univariados,\n  P_Value = p_univariados,\n  Significativo = p_univariados < 0.05\n) %>%\n  dplyr::mutate(Variavel_Desc = sapply(Variavel, obter_descricao))\n\np_f_values <- ggplot2::ggplot(f_df, ggplot2::aes(x = reorder(Variavel_Desc, F_Value), \n                                                 y = F_Value, fill = Significativo)) +\n  ggplot2::geom_col(alpha = 0.8) +\n  ggplot2::geom_text(ggplot2::aes(label = round(F_Value, 1)), hjust = -0.1, size = 3) +\n  ggplot2::coord_flip() +\n  ggplot2::scale_fill_manual(values = c(\"TRUE\" = \"steelblue\", \"FALSE\" = \"gray70\"),\n                            labels = c(\"FALSE\" = \"Não Significativo\", \"TRUE\" = \"Significativo\")) +\n  ggplot2::labs(title = \"Valores F Univariados para Seleção de Variáveis\",\n                subtitle = \"Poder discriminante individual de cada variável\",\n                x = \"Variáveis\", y = \"Estatística F\",\n                fill = \"Significância\\n(p < 0.05)\") +\n  ggplot2::theme_minimal() +\n  ggplot2::theme(plot.title = ggplot2::element_text(size = 14, face = \"bold\"),\n                 axis.text.y = ggplot2::element_text(size = 9))\n\nprint(p_f_values)\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-25-1.png){width=672}\n:::\n\n```{.r .cell-code}\n# Criando gráfico de vetores de atribuição (variáveis no espaço discriminante)\nescores_todos <- predict(modelo_final, amostra_analise)$x\ndf_escores <- data.frame(\n  Funcao1 = escores_todos[, 1],\n  Funcao2 = escores_todos[, 2],\n  Grupo = amostra_analise$X1,\n  Probabilidades = apply(predict(modelo_final, amostra_analise)$posterior, 1, max)\n)\n\n# Adicionando centróides\ndf_centroides <- data.frame(\n  Funcao1 = centroides_discriminantes[, 1],\n  Funcao2 = centroides_discriminantes[, 2],\n  Grupo = factor(rownames(centroides_discriminantes), \n                levels = levels(amostra_analise$X1))\n)\n\n# Escalonando as cargas para melhor visualização\nescala_vetor <- 3  # Fator de escala para os vetores\ncargas_escalonadas <- cargas_discriminantes * escala_vetor\n\n# Preparando dados dos vetores com descrições\nvetores_df <- data.frame(\n  Variavel = rownames(cargas_discriminantes),\n  LD1_start = 0,\n  LD2_start = 0,\n  LD1_end = cargas_escalonadas[, 1],\n  LD2_end = cargas_escalonadas[, 2],\n  Magnitude = sqrt(cargas_discriminantes[, 1]^2 + cargas_discriminantes[, 2]^2),\n  Significativa = rownames(cargas_discriminantes) %in% vars_significativas\n) %>%\n  dplyr::mutate(Variavel_Desc = sapply(Variavel, obter_descricao))\n\n# Gráfico de vetores de atribuição expandidos\np_vetores <- ggplot2::ggplot() +\n  # Pontos dos grupos (mais transparentes para não ofuscar os vetores)\n  ggplot2::geom_point(data = df_escores, ggplot2::aes(x = Funcao1, y = Funcao2, color = Grupo), \n                      alpha = 0.3, size = 1) +\n  # Centróides dos grupos\n  ggplot2::geom_point(data = df_centroides, ggplot2::aes(x = Funcao1, y = Funcao2), \n                      size = 6, shape = 17, color = \"black\") +\n  # LABELS DOS CENTRÓIDES - NOVO\n  ggplot2::geom_text(data = df_centroides, \n                     ggplot2::aes(x = Funcao1, y = Funcao2, label = Grupo),\n                     vjust = -1.5, hjust = 0.5, color = \"black\", \n                     fontface = \"bold\", size = 3.5,\n                     box.padding = 0.5) +\n  # Vetores das variáveis\n  ggplot2::geom_segment(data = vetores_df,\n                        ggplot2::aes(x = LD1_start, y = LD2_start, \n                                     xend = LD1_end, yend = LD2_end,\n                                     color = Significativa, size = Magnitude),\n                        arrow = ggplot2::arrow(length = ggplot2::unit(0.3, \"cm\")),\n                        alpha = 0.8) +\n  # Labels das variáveis com descrições\n  ggplot2::geom_text(data = vetores_df,\n                     ggplot2::aes(x = LD1_end * 1.1, y = LD2_end * 1.1, \n                                  label = Variavel_Desc, color = Significativa),\n                     size = 2.5, fontface = \"bold\") +\n  # Eixos de referência\n  ggplot2::geom_hline(yintercept = 0, linetype = \"dashed\", alpha = 0.5) +\n  ggplot2::geom_vline(xintercept = 0, linetype = \"dashed\", alpha = 0.5) +\n  # Escalas e temas\n  ggplot2::scale_color_manual(values = c(\"FALSE\" = \"gray50\", \"TRUE\" = \"red\")) +\n  ggplot2::scale_size_continuous(range = c(0.5, 2), guide = \"none\") +\n  ggplot2::labs(title = \"Vetores de Atribuição das Variáveis no Espaço Discriminante\",\n                subtitle = paste(\"Vetores mostram contribuição das variáveis para as funções discriminantes\\n\",\n                                \"Triângulos pretos = centróides dos grupos | Escala dos vetores: \", escala_vetor, \"x\"),\n                x = paste(\"Função Discriminante 1 (\", round(variancia_explicada[1], 1), \"%)\"),\n                y = paste(\"Função Discriminante 2 (\", round(variancia_explicada[2], 1), \"%)\"),\n                color = \"Variável\\nSignificativa\") +\n  ggplot2::theme_minimal() +\n  ggplot2::theme(legend.position = \"bottom\",\n                 plot.title = ggplot2::element_text(size = 14, face = \"bold\"),\n                 plot.subtitle = ggplot2::element_text(size = 10))\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in ggplot2::geom_text(data = df_centroides, ggplot2::aes(x = Funcao1, :\nIgnoring unknown parameters: `box.padding`\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: Using `size` aesthetic for lines was deprecated in ggplot2 3.4.0.\nℹ Please use `linewidth` instead.\n```\n\n\n:::\n\n```{.r .cell-code}\nprint(p_vetores)\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-25-2.png){width=672}\n:::\n\n```{.r .cell-code}\n# IDENTIFICAÇÃO DOS GRUPOS DA VARIÁVEL DEPENDENTE\ncat(\"\\n=== IDENTIFICAÇÃO DOS GRUPOS DA VARIÁVEL DEPENDENTE ===\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n=== IDENTIFICAÇÃO DOS GRUPOS DA VARIÁVEL DEPENDENTE ===\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Variável Dependente: X1 (Customer Type)\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nVariável Dependente: X1 (Customer Type)\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Descrição: Tempo de relacionamento com a empresa HBAT\\n\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nDescrição: Tempo de relacionamento com a empresa HBAT\n```\n\n\n:::\n\n```{.r .cell-code}\n# Grupos identificados no gráfico\ngrupos_identificados <- levels(amostra_analise$X1)\nfreq_grupos <- table(amostra_analise$X1)\ncentroides_info <- centroides_discriminantes\n\ncat(\"GRUPOS REPRESENTADOS NO GRÁFICO:\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nGRUPOS REPRESENTADOS NO GRÁFICO:\n```\n\n\n:::\n\n```{.r .cell-code}\nfor(i in 1:length(grupos_identificados)) {\n  grupo_nome <- grupos_identificados[i]\n  freq <- freq_grupos[i]\n  ld1_pos <- round(centroides_info[grupo_nome, \"LD1\"], 2)\n  ld2_pos <- round(centroides_info[grupo_nome, \"LD2\"], 2)\n  \n  cat(sprintf(\"🔺 GRUPO %d: %s\\n\", i, grupo_nome))\n  cat(sprintf(\"   - Frequência: %d casos (%.1f%%)\\n\", \n              freq, (freq/sum(freq_grupos))*100))\n  cat(sprintf(\"   - Posição no gráfico: LD1 = %.2f, LD2 = %.2f\\n\", ld1_pos, ld2_pos))\n  cat(sprintf(\"   - Característica: %s\\n\", \n              switch(i,\n                     \"Clientes com relacionamento recente - percepções iniciais\",\n                     \"Clientes com relacionamento estabelecido - percepções moderadas\", \n                     \"Clientes com relacionamento consolidado - percepções elevadas\")))\n  cat(\"\\n\")\n}\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n🔺 GRUPO 1: Menos de 1 ano\n   - Frequência: 20 casos (33.3%)\n   - Posição no gráfico: LD1 = -1.61, LD2 = 0.31\n   - Característica: Clientes com relacionamento recente - percepções iniciais\n\n🔺 GRUPO 2: De 1 a 5 anos\n   - Frequência: 22 casos (36.7%)\n   - Posição no gráfico: LD1 = 0.26, LD2 = -0.71\n   - Característica: Clientes com relacionamento estabelecido - percepções moderadas\n\n🔺 GRUPO 3: Mais de 5 anos\n   - Frequência: 18 casos (30.0%)\n   - Posição no gráfico: LD1 = 1.47, LD2 = 0.53\n   - Característica: Clientes com relacionamento consolidado - percepções elevadas\n```\n\n\n:::\n\n```{.r .cell-code}\n# Interpretação dos centróides no espaço discriminante\ncat(\"INTERPRETAÇÃO DOS CENTRÓIDES (TRIÂNGULOS PRETOS):\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nINTERPRETAÇÃO DOS CENTRÓIDES (TRIÂNGULOS PRETOS):\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"- Os triângulos pretos representam o 'centro' de cada grupo no espaço discriminante\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n- Os triângulos pretos representam o 'centro' de cada grupo no espaço discriminante\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"- Sua posição indica as características médias de cada grupo\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n- Sua posição indica as características médias de cada grupo\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"- A distância entre centróides mostra o grau de separação entre grupos\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n- A distância entre centróides mostra o grau de separação entre grupos\n```\n\n\n:::\n\n```{.r .cell-code}\n# Análise das posições dos centróides\ncat(\"\\nANÁLISE DAS POSIÇÕES:\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nANÁLISE DAS POSIÇÕES:\n```\n\n\n:::\n\n```{.r .cell-code}\nfor(i in 1:nrow(centroides_info)) {\n  grupo_nome <- rownames(centroides_info)[i]\n  ld1_val <- centroides_info[i, \"LD1\"]\n  ld2_val <- centroides_info[i, \"LD2\"]\n  \n  # Interpretação baseada na posição\n  interpretacao_ld1 <- ifelse(ld1_val > 0, \"valores altos em LD1\", \"valores baixos em LD1\")\n  interpretacao_ld2 <- ifelse(ld2_val > 0, \"valores altos em LD2\", \"valores baixos em LD2\")\n  \n  cat(sprintf(\"- %s: Caracterizado por %s e %s\\n\", \n              grupo_nome, interpretacao_ld1, interpretacao_ld2))\n}\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n- Menos de 1 ano: Caracterizado por valores baixos em LD1 e valores altos em LD2\n- De 1 a 5 anos: Caracterizado por valores altos em LD1 e valores baixos em LD2\n- Mais de 5 anos: Caracterizado por valores altos em LD1 e valores altos em LD2\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"\\nLEGENDA DO GRÁFICO:\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nLEGENDA DO GRÁFICO:\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"🔺 Triângulos pretos = Centróides dos grupos\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n🔺 Triângulos pretos = Centróides dos grupos\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"● Pontos coloridos = Observações individuais por grupo\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n● Pontos coloridos = Observações individuais por grupo\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"→ Vetores vermelhos = Variáveis significativas (p < 0.05)\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n→ Vetores vermelhos = Variáveis significativas (p < 0.05)\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"→ Vetores cinza = Variáveis não significativas\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n→ Vetores cinza = Variáveis não significativas\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"📏 Comprimento do vetor = Magnitude da contribuição discriminante\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n📏 Comprimento do vetor = Magnitude da contribuição discriminante\n```\n\n\n:::\n\n```{.r .cell-code}\n# Interpretação dos vetores\ncat(\"\\n=== INTERPRETAÇÃO DOS VETORES DE ATRIBUIÇÃO ===\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n=== INTERPRETAÇÃO DOS VETORES DE ATRIBUIÇÃO ===\n```\n\n\n:::\n:::\n\n\n\n\n#### 6.4 Análise das Distâncias entre Grupos\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Calculando distâncias Mahalanobis entre centróides\ncentroides_matriz <- as.matrix(centroides_discriminantes)\n\n# Matriz de distâncias entre centróides\nn_grupos <- nrow(centroides_matriz)\ndist_centroides <- matrix(0, n_grupos, n_grupos)\nrownames(dist_centroides) <- rownames(centroides_matriz)\ncolnames(dist_centroides) <- rownames(centroides_matriz)\n\nfor(i in 1:n_grupos) {\n  for(j in 1:n_grupos) {\n    dist_centroides[i, j] <- sqrt(sum((centroides_matriz[i, ] - centroides_matriz[j, ])^2))\n  }\n}\n\nprint(\"Matriz de Distâncias Euclidianas entre Centróides:\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"Matriz de Distâncias Euclidianas entre Centróides:\"\n```\n\n\n:::\n\n```{.r .cell-code}\nprint(round(dist_centroides, 3))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n               Menos de 1 ano De 1 a 5 anos Mais de 5 anos\nMenos de 1 ano          0.000         2.127          3.084\nDe 1 a 5 anos           2.127         0.000          1.737\nMais de 5 anos          3.084         1.737          0.000\n```\n\n\n:::\n\n```{.r .cell-code}\n# Visualização das distâncias como heatmap\ndist_df <- reshape2::melt(dist_centroides)\nnames(dist_df) <- c(\"Grupo1\", \"Grupo2\", \"Distancia\")\n\np_distancias <- ggplot2::ggplot(dist_df, ggplot2::aes(x = Grupo1, y = Grupo2, fill = Distancia)) +\n  ggplot2::geom_tile(color = \"white\") +\n  ggplot2::geom_text(ggplot2::aes(label = round(Distancia, 2)), \n                     color = \"white\", fontface = \"bold\", size = 5) +\n  ggplot2::scale_fill_viridis_c(name = \"Distância\\nEuclidiana\") +\n  ggplot2::labs(title = \"Matriz de Distâncias entre Centróides dos Grupos\",\n                subtitle = \"Distâncias calculadas no espaço discriminante\",\n                x = \"Grupo\", y = \"Grupo\") +\n  ggplot2::theme_minimal() +\n  ggplot2::theme(plot.title = ggplot2::element_text(size = 14, face = \"bold\"),\n                 axis.text.x = ggplot2::element_text(angle = 45, hjust = 1))\n\nprint(p_distancias)\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-26-1.png){width=672}\n:::\n\n```{.r .cell-code}\n# Análise de separação\ndist_matrix_upper <- dist_centroides[upper.tri(dist_centroides)]\n\n# Identificando grupos mais próximos e mais distantes\ndist_indices <- which(dist_centroides == min(dist_matrix_upper), arr.ind = TRUE)[1, ]\ngrupos_proximos <- c(rownames(dist_centroides)[dist_indices[1]], \n                    colnames(dist_centroides)[dist_indices[2]])\n\ndist_indices_max <- which(dist_centroides == max(dist_matrix_upper), arr.ind = TRUE)[1, ]\ngrupos_distantes <- c(rownames(dist_centroides)[dist_indices_max[1]], \n                     colnames(dist_centroides)[dist_indices_max[2]])\n```\n:::\n\n\n\n\n**Interpretação da Análise de Distâncias:**\n\n**Matriz de Distâncias Euclidianas:**\n- **Menor distância**: \"De 1 a 5 anos\" ↔ \"Mais de 5 anos\" (1.737)\n- **Maior distância**: \"Menos de 1 ano\" ↔ \"Mais de 5 anos\" (3.084)\n- **Distância intermediária**: \"Menos de 1 ano\" ↔ \"De 1 a 5 anos\" (2.127)\n\n**Padrões de Similaridade:**\n\n1. **Grupos Intermediário e Maduro são mais próximos**: \n   - Distância de apenas 1.737 unidades\n   - **Interpretação**: Após 1 ano, as percepções começam a convergir\n   - **Implicação**: O primeiro ano é crítico para formar percepções duradouras\n\n2. **Clientes Novos são mais distantes de todos**:\n   - Maior distância dos clientes maduros (3.084)\n   - **Interpretação**: Período inicial tem características muito distintas\n   - **Implicação**: Estratégias específicas necessárias para novos clientes\n\n3. **Progressão Não-Linear**:\n   - A evolução \"Novo → Intermediário → Maduro\" não é uniforme\n   - Maior salto entre \"Novo\" e \"Intermediário\" (2.127)\n   - Menor progressão entre \"Intermediário\" e \"Maduro\" (1.737)\n\n**Insights Gerenciais:**\n\n- **Período Crítico**: Os primeiros 12 meses são fundamentais para retenção\n- **Convergência**: Após 1 ano, clientes tendem a desenvolver percepções similares\n- **Segmentação**: Dois grandes segmentos emergem: \"Novos\" vs. \"Estabelecidos\" (intermediários + maduros)\n\n#### 6.5 Comparação Visual: Espaço Original vs. Espaço Discriminante\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Comparando visualização no espaço original (X6, X18) vs. espaço discriminante\np_original <- ggplot2::ggplot(amostra_analise, ggplot2::aes(x = X6, y = X18, color = X1)) +\n  ggplot2::geom_point(size = 3, alpha = 0.7) +\n  ggplot2::stat_ellipse(level = 0.68, type = \"norm\", size = 1.2) +\n  ggplot2::geom_point(data = centroides, ggplot2::aes(x = X6, y = X18), \n                      size = 8, shape = 17, color = \"black\") +\n  ggplot2::scale_color_brewer(type = \"qual\", palette = \"Set1\") +\n  ggplot2::labs(title = \"Espaço Original\",\n                subtitle = \"Variáveis originais do modelo discriminante\",\n                x = descricoes_variaveis[\"X6\"], \n                y = descricoes_variaveis[\"X18\"],\n                color = \"Grupo\") +\n  ggplot2::theme_minimal() +\n  ggplot2::theme(legend.position = \"bottom\",\n                 plot.title = ggplot2::element_text(size = 12, face = \"bold\"))\n\np_discriminante <- ggplot2::ggplot(df_escores, ggplot2::aes(x = Funcao1, y = Funcao2, color = Grupo)) +\n  ggplot2::geom_point(size = 3, alpha = 0.7) +\n  ggplot2::stat_ellipse(level = 0.68, type = \"norm\", size = 1.2) +\n  ggplot2::geom_point(data = df_centroides, ggplot2::aes(x = Funcao1, y = Funcao2), \n                      size = 8, shape = 17, color = \"black\") +\n  ggplot2::scale_color_brewer(type = \"qual\", palette = \"Set1\") +\n  ggplot2::labs(title = \"Espaço Discriminante (LD1 vs LD2)\",\n                subtitle = \"Funções discriminantes otimizadas para separação\",\n                x = paste(\"LD1 (\", round(variancia_explicada[1], 1), \"%)\"),\n                y = paste(\"LD2 (\", round(variancia_explicada[2], 1), \"%)\"),\n                color = \"Grupo\") +\n  ggplot2::theme_minimal() +\n  ggplot2::theme(legend.position = \"bottom\",\n                 plot.title = ggplot2::element_text(size = 12, face = \"bold\"))\n\n# Combinando os gráficos\ncomparacao <- gridExtra::grid.arrange(\n  p_original, p_discriminante, \n  ncol = 2,\n  top = grid::textGrob(\"Comparação: Espaço Original vs. Espaço Discriminante\", \n                       gp = grid::gpar(fontsize = 16, fontface = \"bold\"))\n)\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-27-1.png){width=672}\n:::\n\n```{.r .cell-code}\nprint(comparacao)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nTableGrob (2 x 2) \"arrange\": 3 grobs\n  z     cells    name                grob\n1 1 (2-2,1-1) arrange      gtable[layout]\n2 2 (2-2,2-2) arrange      gtable[layout]\n3 3 (1-1,1-2) arrange text[GRID.text.321]\n```\n\n\n:::\n\n```{.r .cell-code}\n# Interpretação da comparação\ncat(\"\\n=== INTERPRETAÇÃO DA COMPARAÇÃO ===\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n=== INTERPRETAÇÃO DA COMPARAÇÃO ===\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"- Espaço Original: mostra sobreposição entre grupos\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n- Espaço Original: mostra sobreposição entre grupos\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"- Espaço Discriminante: maximiza separação entre grupos\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n- Espaço Discriminante: maximiza separação entre grupos\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"- A transformação discriminante melhora a separabilidade\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n- A transformação discriminante melhora a separabilidade\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"- LD1 e LD2 são combinações lineares que maximizam discriminação\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n- LD1 e LD2 são combinações lineares que maximizam discriminação\n```\n\n\n:::\n:::\n\n\n\n\n### Estágio 6: Validação dos Resultados\n\n#### 6.6 Matriz de Classificação e Validação\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Classificação da amostra de análise\npredicoes_analise <- predict(modelo_final, amostra_analise)\nmatriz_confusao_analise <- table(Predito = predicoes_analise$class, \n                                Real = amostra_analise$X1)\n\nprint(\"Matriz de Classificação - Amostra de Análise:\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"Matriz de Classificação - Amostra de Análise:\"\n```\n\n\n:::\n\n```{.r .cell-code}\nprint(matriz_confusao_analise)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                Real\nPredito          Menos de 1 ano De 1 a 5 anos Mais de 5 anos\n  Menos de 1 ano             16             2              0\n  De 1 a 5 anos               3            14              1\n  Mais de 5 anos              1             6             17\n```\n\n\n:::\n\n```{.r .cell-code}\n# Taxa de acerto geral\nacerto_geral_analise <- sum(diag(matriz_confusao_analise)) / sum(matriz_confusao_analise)\n\n# Taxa de acerto por grupo\nacerto_por_grupo_analise <- diag(matriz_confusao_analise) / rowSums(matriz_confusao_analise)\nprint(\"Taxa de Acerto por Grupo (Análise):\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"Taxa de Acerto por Grupo (Análise):\"\n```\n\n\n:::\n\n```{.r .cell-code}\nprint(round(acerto_por_grupo_analise * 100, 1))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nMenos de 1 ano  De 1 a 5 anos Mais de 5 anos \n          88.9           77.8           70.8 \n```\n\n\n:::\n\n```{.r .cell-code}\n# Visualização da matriz de confusão\nmatriz_conf_df <- as.data.frame(matriz_confusao_analise)\nnames(matriz_conf_df) <- c(\"Predito\", \"Real\", \"Freq\")\n\np_matriz_conf <- ggplot2::ggplot(matriz_conf_df, ggplot2::aes(x = Real, y = Predito, fill = Freq)) +\n  ggplot2::geom_tile(color = \"white\") +\n  ggplot2::geom_text(ggplot2::aes(label = Freq), color = \"white\", size = 6, fontface = \"bold\") +\n  ggplot2::scale_fill_viridis_c(name = \"Frequência\") +\n  ggplot2::labs(title = \"Matriz de Confusão - Amostra de Análise\",\n                subtitle = paste(\"Taxa de Acerto Geral:\", round(acerto_geral_analise * 100, 1), \"%\"),\n                x = \"Grupo Real\", y = \"Grupo Predito\") +\n  ggplot2::theme_minimal() +\n  ggplot2::theme(plot.title = ggplot2::element_text(size = 14, face = \"bold\"),\n                 axis.text.x = ggplot2::element_text(angle = 45, hjust = 1))\n\nprint(p_matriz_conf)\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-28-1.png){width=672}\n:::\n:::\n\n\n\n\n**Taxa de Acerto Geral (Análise)**: 78.3%\n\n**Taxa de Acerto por Grupo (Análise)**:\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\n|Grupo          | Taxa.de.Acerto....|\n|:--------------|------------------:|\n|Menos de 1 ano |               88.9|\n|De 1 a 5 anos  |               77.8|\n|Mais de 5 anos |               70.8|\n\n\n:::\n:::\n\n\n\n\n#### 6.7 Validação Cruzada\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Função para validação cruzada\nvalidacao_cruzada <- function(dados, formula) {\n  n <- nrow(dados)\n  predicoes <- character(n)\n  \n  for(i in 1:n) {\n    # Treina modelo sem a observação i\n    dados_treino <- dados[-i, ]\n    modelo_temp <- MASS::lda(formula, data = dados_treino)\n    \n    # Prediz a observação i\n    predicao_temp <- predict(modelo_temp, dados[i, ])\n    predicoes[i] <- as.character(predicao_temp$class)\n  }\n  \n  return(factor(predicoes, levels = levels(dados$X1)))\n}\n\n# Aplicando validação cruzada\npredicoes_cv <- validacao_cruzada(amostra_analise, X1 ~ X6 + X18)\nmatriz_confusao_cv <- table(Predito = predicoes_cv, Real = amostra_analise$X1)\n\nprint(\"Matriz de Classificação - Validação Cruzada:\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"Matriz de Classificação - Validação Cruzada:\"\n```\n\n\n:::\n\n```{.r .cell-code}\nprint(matriz_confusao_cv)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                Real\nPredito          Menos de 1 ano De 1 a 5 anos Mais de 5 anos\n  Menos de 1 ano             16             2              0\n  De 1 a 5 anos               3            14              1\n  Mais de 5 anos              1             6             17\n```\n\n\n:::\n\n```{.r .cell-code}\n# Taxa de acerto validação cruzada\nacerto_geral_cv <- sum(diag(matriz_confusao_cv)) / sum(matriz_confusao_cv)\n```\n:::\n\n\n\n\n**Taxa de Acerto Geral (Validação Cruzada)**: 78.3%\n\n#### 6.8 Validação Externa\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Classificação da amostra de validação\npredicoes_validacao <- predict(modelo_final, amostra_validacao)\nmatriz_confusao_validacao <- table(Predito = predicoes_validacao$class, \n                                  Real = amostra_validacao$X1)\n\nprint(\"Matriz de Classificação - Amostra de Validação:\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"Matriz de Classificação - Amostra de Validação:\"\n```\n\n\n:::\n\n```{.r .cell-code}\nprint(matriz_confusao_validacao)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                Real\nPredito          Menos de 1 ano De 1 a 5 anos Mais de 5 anos\n  Menos de 1 ano             10             1              0\n  De 1 a 5 anos               1            10              4\n  Mais de 5 anos              1             2             11\n```\n\n\n:::\n\n```{.r .cell-code}\n# Taxa de acerto amostra de validação\nacerto_geral_validacao <- sum(diag(matriz_confusao_validacao)) / sum(matriz_confusao_validacao)\n\n# Taxa de acerto por grupo\nacerto_por_grupo_validacao <- diag(matriz_confusao_validacao) / rowSums(matriz_confusao_validacao)\nprint(\"Taxa de Acerto por Grupo (Validação):\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"Taxa de Acerto por Grupo (Validação):\"\n```\n\n\n:::\n\n```{.r .cell-code}\nprint(round(acerto_por_grupo_validacao * 100, 1))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nMenos de 1 ano  De 1 a 5 anos Mais de 5 anos \n          90.9           66.7           78.6 \n```\n\n\n:::\n:::\n\n\n\n\n**Taxa de Acerto Geral (Validação)**: 77.5%\n\n#### 6.9 Critérios de Chance\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Calculando critérios de chance\ntamanhos_grupos <- table(amostra_analise$X1)\nproporcoes_grupos <- tamanhos_grupos / sum(tamanhos_grupos)\n\n# Critério de chance proporcional\ncriterio_chance_proporcional <- sum(proporcoes_grupos^2) * 100\n\n# Critério de chance máxima\ncriterio_chance_maxima <- max(proporcoes_grupos) * 100\n\n# Gráfico de comparação das taxas de acerto\ntaxas_acerto <- data.frame(\n  Metodo = c(\"Análise\", \"Validação Cruzada\", \"Validação Externa\", \n             \"Critério Proporcional\", \"Critério Máximo\"),\n  Taxa = c(acerto_geral_analise * 100, \n           acerto_geral_cv * 100,\n           acerto_geral_validacao * 100,\n           criterio_chance_proporcional,\n           criterio_chance_maxima),\n  Tipo = c(\"Modelo\", \"Modelo\", \"Modelo\", \"Referência\", \"Referência\")\n)\n\np_performance <- ggplot2::ggplot(taxas_acerto, ggplot2::aes(x = reorder(Metodo, Taxa), y = Taxa, fill = Tipo)) +\n  ggplot2::geom_col(alpha = 0.8, width = 0.7) +\n  ggplot2::geom_text(ggplot2::aes(label = paste0(round(Taxa, 1), \"%\")), \n                     hjust = -0.1, size = 4, fontface = \"bold\") +\n  ggplot2::coord_flip() +\n  ggplot2::scale_fill_manual(values = c(\"Modelo\" = \"steelblue\", \"Referência\" = \"coral\")) +\n  ggplot2::labs(title = \"Comparação das Taxas de Acerto\",\n                subtitle = \"Modelo vs. Critérios de Chance\",\n                x = \"Método de Validação\", \n                y = \"Taxa de Acerto (%)\",\n                fill = \"Tipo\") +\n  ggplot2::theme_minimal() +\n  ggplot2::theme(legend.position = \"bottom\",\n                 plot.title = ggplot2::element_text(size = 14, face = \"bold\"))\n\nprint(p_performance)\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-32-1.png){width=672}\n:::\n:::\n\n\n\n\n**Critérios de Chance:**\n\n- **Critério de Chance Proporcional**: 33.6%\n- **Critério de Chance Máxima**: 36.7%\n\n**Comparação com Resultados Obtidos:**\n\n- Taxa de Acerto Análise: 78.3% vs Critério Proporcional: 33.6%\n- Taxa de Acerto Validação Cruzada: 78.3% vs Critério Proporcional: 33.6%  \n- Taxa de Acerto Validação: 77.5% vs Critério Proporcional: 33.6%\n\n### Resumo da Interpretação Gerencial\n\nOs resultados da análise discriminante revelam insights importantes sobre a diferenciação de clientes baseada no tempo de relacionamento. Com o dataset completo analisado, identificamos que de 13 variáveis independentes testadas, apenas 2 foram suficientes para uma discriminação efetiva.\n\n#### Principais Descobertas:\n\n1. **Variáveis Discriminantes**: X6 (Product Quality) e X18 (Delivery Speed) são os principais diferenciadores, representando aproximadamente 100% da variância discriminante total.\n\n2. **Precisão do Modelo**: O modelo alcança alta taxa de acertos na amostra de análise, superando significativamente os critérios de chance.\n\n3. **Diferenças entre Grupos**: \n   - **Clientes novos** (< 1 ano): Menores percepções de qualidade e velocidade\n   - **Clientes intermediários** (1-5 anos): Percepções moderadas\n   - **Clientes estabelecidos** (> 5 anos): Maiores percepções de qualidade e velocidade\n\n#### Implicações Gerenciais:\n\n- **Foco na Qualidade**: Investir na melhoria da qualidade do produto é fundamental para reter clientes\n- **Otimização de Entregas**: A velocidade de entrega é um diferencial competitivo crítico\n- **Segmentação**: Os 3 grupos identificados requerem estratégias diferenciadas\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Médias dos grupos para interpretação\nmedias_grupos <- aggregate(amostra_analise[, variaveis_independentes], \n                          by = list(amostra_analise$X1), FUN = mean)\nnames(medias_grupos)[1] <- \"Grupo\"\n\n# Corrigindo erro na impressão das médias dos grupos\nmedias_grupos_numericas <- medias_grupos[, -1]  # Remove coluna 'Grupo'\nrownames(medias_grupos_numericas) <- medias_grupos$Grupo\n\nprint(\"Médias dos Grupos nas Variáveis Independentes:\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"Médias dos Grupos nas Variáveis Independentes:\"\n```\n\n\n:::\n\n```{.r .cell-code}\nprint(round(medias_grupos_numericas, 2))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                 X6   X7   X8   X9  X10  X11  X12  X13  X14  X15  X16  X17  X18\nMenos de 1 ano 6.99 3.56 5.28 4.30 3.83 4.72 4.75 7.42 5.98 5.38 3.53 4.29 3.14\nDe 1 a 5 anos  7.34 3.85 5.30 5.99 4.27 5.65 5.49 7.75 5.98 4.91 4.70 5.54 4.27\nMais de 5 anos 9.18 3.73 5.82 5.92 4.01 7.00 5.12 5.99 6.32 5.37 4.65 3.94 4.17\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"\\n=== INTERPRETAÇÃO DAS FUNÇÕES DISCRIMINANTES ===\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n=== INTERPRETAÇÃO DAS FUNÇÕES DISCRIMINANTES ===\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Função 1: Diferencia principalmente entre Grupo 1 e Grupos 2-3\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nFunção 1: Diferencia principalmente entre Grupo 1 e Grupos 2-3\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Função 2: Diferencia principalmente entre Grupo 3 e Grupos 1-2\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nFunção 2: Diferencia principalmente entre Grupo 3 e Grupos 1-2\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"\\n=== VARIÁVEIS MAIS IMPORTANTES ===\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n=== VARIÁVEIS MAIS IMPORTANTES ===\n```\n\n\n:::\n\n```{.r .cell-code}\nif(exists(\"indice_potencia_ordenado\")) {\n  cat(\"Por Índice de Potência:\\n\")\n  print(names(indice_potencia_ordenado)[1:min(5, length(indice_potencia_ordenado))])\n}\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nPor Índice de Potência:\n[1] \"X6\"  \"X11\" \"X17\" \"X18\" \"X9\" \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"\\nPor Razão F Univariada:\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nPor Razão F Univariada:\n```\n\n\n:::\n\n```{.r .cell-code}\nprint(names(razoes_f_ordenadas)[1:min(5, length(razoes_f_ordenadas))])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"X18\" \"X6\"  \"X9\"  \"X11\" \"X16\"\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"\\n=== RESUMO FINAL ===\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n=== RESUMO FINAL ===\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Modelo discriminante final: X1 ~ X6 + X18\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nModelo discriminante final: X1 ~ X6 + X18\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Variáveis selecionadas:\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nVariáveis selecionadas:\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"- X6: Qualidade do produto\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n- X6: Qualidade do produto\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"- X18: Velocidade de entrega\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n- X18: Velocidade de entrega\n```\n\n\n:::\n\n```{.r .cell-code}\nif(exists(\"modelo_stepwise\")) {\n  cat(\"\\nVariáveis selecionadas pelo procedimento stepwise:\\n\")\n  print(modelo_stepwise$formula)\n}\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nVariáveis selecionadas pelo procedimento stepwise:\n[1] \"X1 ~ X6 + X18\"\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"\\n=== CONCLUSÕES GERENCIAIS ===\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n=== CONCLUSÕES GERENCIAIS ===\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"1. A qualidade do produto (X6) e velocidade de entrega (X18) são os principais diferenciadores entre os grupos de clientes.\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n1. A qualidade do produto (X6) e velocidade de entrega (X18) são os principais diferenciadores entre os grupos de clientes.\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"2. O modelo consegue discriminar bem entre os três grupos de tempo de relacionamento.\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n2. O modelo consegue discriminar bem entre os três grupos de tempo de relacionamento.\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"3. Clientes de longo prazo valorizam mais qualidade e velocidade de entrega.\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n3. Clientes de longo prazo valorizam mais qualidade e velocidade de entrega.\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"4. Ações de melhoria devem focar nestas duas dimensões para reter clientes.\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n4. Ações de melhoria devem focar nestas duas dimensões para reter clientes.\n```\n\n\n:::\n:::\n\n\n\n\n**Análise das Médias por Grupo:**\n\nOs resultados mostram um padrão claro de evolução das percepções com o tempo de relacionamento, com melhorias progressivas nas percepções de qualidade e velocidade de entrega conforme aumenta o tempo de relacionamento com a empresa.\n\n### Apêndice: Informações Técnicas do Dataset\n\n#### Características do Dataset HBAT\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Informações sobre o dataset após limpeza\ncat(\"=== CARACTERÍSTICAS DO DATASET FINAL ===\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n=== CARACTERÍSTICAS DO DATASET FINAL ===\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Total de observações:\", nrow(hbat_clean), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nTotal de observações: 100 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Variáveis independentes analisadas:\", length(variaveis_independentes), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nVariáveis independentes analisadas: 13 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Grupos da variável dependente:\", nlevels(hbat_clean$X1), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nGrupos da variável dependente: 3 \n```\n\n\n:::\n\n```{.r .cell-code}\n# Distribuição dos grupos\ndist_grupos <- table(hbat_clean$X1)\nprop_grupos <- prop.table(dist_grupos) * 100\n\ncat(\"\\nDistribuição dos grupos:\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nDistribuição dos grupos:\n```\n\n\n:::\n\n```{.r .cell-code}\nfor(i in 1:length(dist_grupos)) {\n  cat(\"- \", names(dist_grupos)[i], \": \", dist_grupos[i], \" casos (\", \n      round(prop_grupos[i], 1), \"%)\\n\", sep = \"\")\n}\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n- Menos de 1 ano: 32 casos (32%)\n- De 1 a 5 anos: 35 casos (35%)\n- Mais de 5 anos: 33 casos (33%)\n```\n\n\n:::\n:::\n\n\n\n\n#### Qualidade dos Dados\n\n- **Missing values**: Removidos através de listwise deletion\n- **Balanceamento**: Dataset relativamente balanceado entre os grupos\n- **Escala das variáveis**: Todas as variáveis independentes estão na escala de 0-10\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Informações detalhadas sobre o dataset HBAT\ncat(\"=== INFORMAÇÕES DO DATASET HBAT ===\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n=== INFORMAÇÕES DO DATASET HBAT ===\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Total de observações:\", nrow(hbat_clean), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nTotal de observações: 100 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Variáveis independentes:\", length(variaveis_independentes), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nVariáveis independentes: 13 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Grupos da variável dependente:\", nlevels(hbat_clean$X1), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nGrupos da variável dependente: 3 \n```\n\n\n:::\n\n```{.r .cell-code}\n# Descrição das variáveis (baseado nos labels originais) - ATUALIZADO\ncat(\"\\n=== DESCRIÇÃO COMPLETA DAS VARIÁVEIS ===\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n=== DESCRIÇÃO COMPLETA DAS VARIÁVEIS ===\n```\n\n\n:::\n\n```{.r .cell-code}\nfor(var in names(descricoes_variaveis)) {\n  cat(var, \"-\", descricoes_variaveis[var], \"\\n\")\n}\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nX1 - Customer Type \nX6 - Product Quality \nX7 - E-Commerce Activities \nX8 - Technical Support \nX9 - Complaint Resolution \nX10 - Advertising \nX11 - Product Line \nX12 - Salesforce Image \nX13 - Competitive Pricing \nX14 - Warranty & Claims \nX15 - New Products \nX16 - Ordering & Billing \nX17 - Price Flexibility \nX18 - Delivery Speed \n```\n\n\n:::\n\n```{.r .cell-code}\n# Estatísticas descritivas finais\ncat(\"\\n=== ESTATÍSTICAS DESCRITIVAS FINAIS ===\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n=== ESTATÍSTICAS DESCRITIVAS FINAIS ===\n```\n\n\n:::\n\n```{.r .cell-code}\nprint(summary(hbat_clean))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n              X1           X6               X7              X8       \n Menos de 1 ano:32   Min.   : 5.000   Min.   :2.200   Min.   :1.300  \n De 1 a 5 anos :35   1st Qu.: 6.575   1st Qu.:3.275   1st Qu.:4.250  \n Mais de 5 anos:33   Median : 8.000   Median :3.600   Median :5.400  \n                     Mean   : 7.810   Mean   :3.672   Mean   :5.365  \n                     3rd Qu.: 9.100   3rd Qu.:3.925   3rd Qu.:6.625  \n                     Max.   :10.000   Max.   :5.700   Max.   :8.500  \n       X9             X10             X11             X12       \n Min.   :2.600   Min.   :1.900   Min.   :2.300   Min.   :2.900  \n 1st Qu.:4.600   1st Qu.:3.175   1st Qu.:4.700   1st Qu.:4.500  \n Median :5.450   Median :4.000   Median :5.750   Median :4.900  \n Mean   :5.442   Mean   :4.010   Mean   :5.805   Mean   :5.123  \n 3rd Qu.:6.325   3rd Qu.:4.800   3rd Qu.:6.800   3rd Qu.:5.800  \n Max.   :7.800   Max.   :6.500   Max.   :8.400   Max.   :8.200  \n      X13             X14             X15            X16             X17      \n Min.   :3.700   Min.   :4.100   Min.   :1.70   Min.   :2.000   Min.   :2.60  \n 1st Qu.:5.875   1st Qu.:5.400   1st Qu.:4.10   1st Qu.:3.700   1st Qu.:3.70  \n Median :7.100   Median :6.100   Median :5.00   Median :4.400   Median :4.35  \n Mean   :6.974   Mean   :6.043   Mean   :5.15   Mean   :4.278   Mean   :4.61  \n 3rd Qu.:8.400   3rd Qu.:6.600   3rd Qu.:6.30   3rd Qu.:4.800   3rd Qu.:5.60  \n Max.   :9.900   Max.   :8.100   Max.   :9.50   Max.   :6.700   Max.   :7.30  \n      X18       \n Min.   :1.600  \n 1st Qu.:3.400  \n Median :3.900  \n Mean   :3.886  \n 3rd Qu.:4.425  \n Max.   :5.500  \n```\n\n\n:::\n:::\n",
    "supporting": [
      "index_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}